import { describe, expect, it } from 'vitest';
import {
  asActorId,
  asAttestationId,
  asIdempotencyKey,
  asNamespaceId,
  asNodeId,
  asProcessorId,
  asSubjectId,
  normalizeWriteCommand,
  type WriteCommand,
} from '../../src/index.js';
import { ProposalNotFoundError, ProposalValidationError } from '../../src/proposals/errors.js';
import { createProposalsTestHarness } from './harness.js';

const NAMESPACE = asNamespaceId('canonical.global');

function factMutation(id: string, overrides: Partial<WriteCommand> = {}): WriteCommand {
  return {
    namespace: NAMESPACE,
    subject: asSubjectId('subject-1'),
    nodeMutations: [{ op: 'create', nodeId: asNodeId(id), nodeType: 'fact', payload: { statement: `claim ${id}` }, confidence: 0.9 }],
    edgeMutations: [],
    expectedNamespaceRevision: null,
    idempotencyKey: asIdempotencyKey(`write-${id}`),
    actorId: asActorId('actor-1'),
    actorClass: 'human',
    provenanceInput: { sources: [{ kind: 'external', id: 'src-1' }] },
    ...overrides,
  };
}

describe('DurableProposalService: review measurements', () => {
  it('counts proposals by status, accepted/rejected totals, and an acceptance rate', async () => {
    const harness = createProposalsTestHarness();

    const accepted = await harness.service.propose({ mutation: factMutation('n-1'), supportingObservationIds: [], idempotencyKey: 'propose-1' });
    if (accepted.outcome !== 'created') throw new Error('unreachable');
    const { mutationHash } = normalizeWriteCommand(factMutation('n-1'));
    harness.attestationVerifier.register({
      id: asAttestationId('att-1'),
      reviewerId: asActorId('reviewer-1'),
      approvedAt: harness.clock.now(),
      proposalId: accepted.proposal.id,
      proposalVersion: 1,
      targetRevision: null,
      mutationHash,
      channel: 'test',
      verifierMeta: {},
    });
    await harness.service.accept(accepted.proposal.id, {
      expectedVersion: 1,
      expectedTargetRevision: null,
      attestationId: asAttestationId('att-1'),
      actorId: asActorId('reviewer-1'),
      channel: 'test',
      reviewBatchId: 'batch-1',
      idempotencyKey: 'accept-1',
    });

    const rejected = await harness.service.propose({ mutation: factMutation('n-2'), supportingObservationIds: [], idempotencyKey: 'propose-2' });
    if (rejected.outcome !== 'created') throw new Error('unreachable');
    await harness.service.reject(rejected.proposal.id, {
      expectedVersion: 1,
      actorId: asActorId('reviewer-1'),
      reason: 'not credible',
      idempotencyKey: 'reject-1',
    });

    await harness.service.propose({ mutation: factMutation('n-3'), supportingObservationIds: [], idempotencyKey: 'propose-3' });

    const measurements = await harness.service.reviewMeasurements({ from: '2000-01-01T00:00:00.000Z', to: '2100-01-01T00:00:00.000Z' });
    expect(measurements.countsByStatus.pending).toBe(1);
    expect(measurements.countsByStatus.accepted).toBe(1);
    expect(measurements.countsByStatus.rejected).toBe(1);
    expect(measurements.acceptedCount).toBe(1);
    expect(measurements.rejectedCount).toBe(1);
    expect(measurements.acceptanceRate).toBe(0.5);
    expect(measurements.firstReviewLatencyMsAvg).not.toBeNull();
    expect(measurements.batchSizes['batch-1']).toBe(1);
    expect(measurements.reviewerMinutes['reviewer-1']).toBeGreaterThanOrEqual(0);
    harness.connection.close();
  });

  it('scopes counts to the requested namespace', async () => {
    const harness = createProposalsTestHarness();
    await harness.service.propose({ mutation: factMutation('n-1'), supportingObservationIds: [], idempotencyKey: 'propose-1' });

    const scoped = await harness.service.reviewMeasurements({
      namespace: asNamespaceId('canonical.project.other'),
      from: '2000-01-01T00:00:00.000Z',
      to: '2100-01-01T00:00:00.000Z',
    });
    expect(scoped.countsByStatus.pending).toBe(0);

    const unscoped = await harness.service.reviewMeasurements({ from: '2000-01-01T00:00:00.000Z', to: '2100-01-01T00:00:00.000Z' });
    expect(unscoped.countsByStatus.pending).toBe(1);
    harness.connection.close();
  });
});

describe('DurableProposalService: audit samples', () => {
  it('lists pending samples generated by ai-with-rails writes and allows marking one reviewed exactly once', async () => {
    const harness = createProposalsTestHarness();
    const aiNamespace = asNamespaceId('memory.community.topic-1');
    const processorId = asProcessorId('proc-1');

    for (let i = 0; i < 10; i += 1) {
      await harness.orchestrator.write({
        namespace: aiNamespace,
        subject: asSubjectId('subject-1'),
        nodeMutations: [{ op: 'create', nodeId: asNodeId(`n-${i}`), nodeType: 'observation', payload: { description: `item ${i}` }, confidence: 0.7 }],
        edgeMutations: [],
        expectedNamespaceRevision: null,
        idempotencyKey: asIdempotencyKey(`idem-${i}`),
        actorId: asActorId('actor-1'),
        actorClass: 'processor',
        provenanceInput: { sources: [{ kind: 'external', id: 'src-1' }], processorId },
      });
    }

    const pending = await harness.service.pendingAuditSamples(aiNamespace);
    expect(pending).toHaveLength(1);
    expect(pending[0]!.namespaceRevision).toBe(10);
    expect(pending[0]!.reviewed).toBe(false);

    const reviewed = await harness.service.markAuditSampleReviewed(pending[0]!.sampleId, {
      reviewerId: asActorId('reviewer-1'),
      verdict: 'ok',
      note: 'looks fine',
      at: harness.clock.now(),
    });
    expect(reviewed.reviewed).toBe(true);
    expect(await harness.service.pendingAuditSamples(aiNamespace)).toHaveLength(0);

    await expect(
      harness.service.markAuditSampleReviewed(pending[0]!.sampleId, { reviewerId: asActorId('reviewer-1'), verdict: 'ok', at: harness.clock.now() }),
    ).rejects.toThrow(ProposalValidationError);
    harness.connection.close();
  });

  it('throws for an unknown audit sample id', async () => {
    const harness = createProposalsTestHarness();
    await expect(
      harness.service.markAuditSampleReviewed('missing', { reviewerId: asActorId('reviewer-1'), verdict: 'ok', at: harness.clock.now() }),
    ).rejects.toThrow(ProposalNotFoundError);
    harness.connection.close();
  });
});
