import { parse, stringify } from 'yaml';
import type { NamespaceId } from '../../domain/ids.js';
import type { RevisionRecord } from '../../ports/repository.js';
import { ADAPTER_MAPPING_VERSION } from './config.js';

/** A non-native edge (derived_from/contradicts/supersedes) with no dossier-field representation. */
export interface SidecarEdgeRecord {
  id: string;
  kind: string;
  sourceId: string;
  targetId: string;
  provenance: unknown;
  revision: unknown;
}

/** The latest known provenance/revision metadata for one node, keyed by node id. */
export interface SidecarNodeProvenance {
  provenance: unknown;
  revision: unknown;
}

export interface NamespaceSidecar {
  mappingVersion: number;
  nodeProvenance: Record<string, SidecarNodeProvenance>;
  edges: SidecarEdgeRecord[];
  revisions: RevisionRecord[];
}

export function emptySidecar(): NamespaceSidecar {
  return { mappingVersion: ADAPTER_MAPPING_VERSION, nodeProvenance: {}, edges: [], revisions: [] };
}

/** Filesystem-safe stand-in for a namespace id, used as the sidecar's file basename. */
export function encodeNamespaceForPath(namespace: NamespaceId): string {
  return String(namespace).replace(/[^a-zA-Z0-9_.-]/g, '_');
}

export function sidecarRelativePath(namespace: NamespaceId): string {
  return `.algerknown/governed/namespaces/${encodeNamespaceForPath(namespace)}.yaml`;
}

export function parseSidecar(content: string): NamespaceSidecar {
  const parsed = parse(content) as Partial<NamespaceSidecar> | null;
  return {
    mappingVersion: parsed?.mappingVersion ?? ADAPTER_MAPPING_VERSION,
    nodeProvenance: parsed?.nodeProvenance ?? {},
    edges: parsed?.edges ?? [],
    revisions: parsed?.revisions ?? [],
  };
}

export function serializeSidecar(sidecar: NamespaceSidecar): string {
  return `# Governed metadata overlay -- generated by @algerknown/governed's algerknown adapter.\n# Do not hand-edit: content and node/edge identity live in the dossier file itself.\n${stringify(
    sidecar,
  )}`;
}
