/**
 * Vendored Unicode 15.0.0 White_Space property ranges.
 * Source: https://www.unicode.org/Public/15.0.0/ucd/PropList.txt, White_Space entries only
 * (Pattern_White_Space entries are excluded; they are a distinct, narrower property).
 *
 * Generated by packages/core/scripts/generate-unicode-data.mjs — see that script's
 * header and docs/unicode-normalization.md for regeneration instructions.
 */

// Inclusive [start, end] code point ranges, sorted ascending, non-overlapping.
export const WHITE_SPACE_RANGES: ReadonlyArray<readonly [number, number]> = [
  [0x9,0xD], [0x20,0x20], [0x85,0x85], [0xA0,0xA0], [0x1680,0x1680], [0x2000,0x200A], [0x2028,0x2028], [0x2029,0x2029], [0x202F,0x202F], [0x205F,0x205F], [0x3000,0x3000]
];

export const WHITE_SPACE_UNICODE_VERSION = '15.0.0';
